//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInvoice.Repository.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice03
    {
        public int id { get; set; }
        public Nullable<int> InvCateID { get; set; }
        public Nullable<decimal> No { get; set; }
        public string Data { get; set; }
        public string Serial { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> ComID { get; set; }
        public string ComName { get; set; }
        public string ComPhone { get; set; }
        public string ComFax { get; set; }
        public string ComAddress { get; set; }
        public string ComTaxCode { get; set; }
        public string ComBankName { get; set; }
        public string ComBankNo { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public string CusEmail { get; set; }
        public string Buyer { get; set; }
        public string CusAddress { get; set; }
        public string CusPhone { get; set; }
        public string CusBankName { get; set; }
        public string CusBankNo { get; set; }
        public string CusTaxCode { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<double> VATRate { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AmountInWords { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> Converted { get; set; }
        public Nullable<int> CusSignStatus { get; set; }
        public string CreateBy { get; set; }
        public string PublishBy { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> ArisingDate { get; set; }
        public string ProcessInvNote { get; set; }
        public string AttachPath { get; set; }
        public string ContainerNumber { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractNumber { get; set; }
        public string FromWareHouseName { get; set; }
        public string ToWareHouseName { get; set; }
        public string DeliveryBy { get; set; }
        public string DeliveryOrderBy { get; set; }
        public Nullable<System.DateTime> DeliveryOrderDate { get; set; }
        public string DeliveryOrderNumber { get; set; }
        public string TransportationMethod { get; set; }
        public string Trans { get; set; }
        public string SearchKey { get; set; }
        public string Fkey { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public Nullable<decimal> VatAmount0 { get; set; }
        public Nullable<decimal> GrossValue0 { get; set; }
        public Nullable<decimal> VatAmount5 { get; set; }
        public Nullable<decimal> GrossValue5 { get; set; }
        public Nullable<decimal> VatAmount10 { get; set; }
        public Nullable<decimal> GrossValue10 { get; set; }
        public Nullable<bool> Certified { get; set; }
        public string CertifiedID { get; set; }
        public string CertifiedData { get; set; }
        public string ExchangeRate { get; set; }
        public string BranchCode { get; set; }
        public string Name { get; set; }
    }
}
