//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInvoice.Entity.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingAccount
    {
        public int AccountingAccID { get; set; }
        public string AccountingAccCode { get; set; }
        public string AccountingAccNo { get; set; }
        public string AccountingAccName { get; set; }
        public string Description { get; set; }
    }
}
