//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInvoice.Entity.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustInv
    {
        public int id { get; set; }
        public Nullable<int> InvId { get; set; }
        public Nullable<int> AdjustInvId { get; set; }
        public string Description { get; set; }
        public string Pattern { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ComID { get; set; }
        public string Attachefile { get; set; }
    }
}
