//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInvoice.Entity.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public int BusinessID { get; set; }
        public int ComID { get; set; }
        public string TaxCode { get; set; }
        public string BusinessCode { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> BusinessStatus { get; set; }
        public int PublishInvID { get; set; }
        public bool IsDelete { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedUserID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string InvPattern { get; set; }
        public string InvSerial { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> AccountingID { get; set; }
    }
}
