//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInvoice.Entity.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int id { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankNumber { get; set; }
        public string Descriptions { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string RepresentPerson { get; set; }
        public string TaxCode { get; set; }
        public string AccountName { get; set; }
        public string Domain { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public string ParentName { get; set; }
        public string PortalLink { get; set; }
        public Nullable<int> Type { get; set; }
        public string ContactPerson { get; set; }
        public string TaxAuthorityCode { get; set; }
        public string ContactEmail { get; set; }
        public string ExtEmail { get; set; }
        public Nullable<int> SignedDateOption { get; set; }
    }
}
