//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInvoice.Entity.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string Buyer { get; set; }
        public string Name { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Descriptions { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string CCEmail { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string RepresentPerson { get; set; }
        public string TaxCode { get; set; }
        public string AccountName { get; set; }
        public string Code { get; set; }
        public Nullable<int> ComID { get; set; }
        public string SignatureImage { get; set; }
        public Nullable<int> CusType { get; set; }
        public string SerialCert { get; set; }
        public Nullable<int> DeliverMethod { get; set; }
        public Nullable<int> Approve { get; set; }
        public Nullable<int> ApprovedByUser { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
