//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eInvoice.Entity.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDepartment
    {
        public int id { get; set; }
        public Nullable<int> ComID { get; set; }
        public string username { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    }
}
